### ISSUE TITLE
Path for glyphicons in bootstrap.css is wrong in compiled HTML

### ISSUE THREAD

**Issue by imrahil** [arthurwolf/fabrica#6]
it's _../fonts/glyphicons..._ but should be _static/fonts/glyphicons..._

to avoid changes in oryginal bootstrap.css this should be handled in compile.pl script

**Comment by arthurwolf** [comment]
Wait, this isn't in the index.tpl file. So it's like, in the bootstrap css
??

On Sat, May 7, 2016 at 10:12 PM, Jarek Szczepanski <notifications@github.com

> wrote:
> 
> it's _../fonts/glyphicons..._ but should be _static/fonts/glyphicons..._
> 
> to avoid changes in oryginal bootstrap.css this should be handled in
> compile.pl script
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/arthurwolf/fabrica/issues/6

## 

Courage et bonne humeur.

**Comment by imrahil** [comment]
yup. it's request from bootstrap.min.css

**Comment by arthurwolf** [comment]
It is so much work to add this to the compile script ... I just did it manually. This project is still young, let's be pirates for a little while longer :)
