### ISSUE TITLE
Wrong regexp for configuration parser

### ISSUE THREAD

**Issue by imrahil** [arthurwolf/fabrica#7]
I'm too lazy to prepare pull request :)
https://github.com/arthurwolf/fabrica/blob/gh-pages/src/core/configuration.js#L23
regexp don't handle lines without comments
better version:
`var match = line.match(/^([\w_\-\.]*)\s+(.*?)(?!\S)/);`

**Comment by arthurwolf** [comment]
Done :) We'll see if it breaks anything :)

Thanks a lot for these issues btw, keep them coming.
